name: Readme Fetch
description: Generate your profile/readme in (neo)fetch style
inputs:
  dry_run:
    description: Run without committing
    required: false
    default: no
  user:
    description: Your username
    required: true
  host:
    description: Your hostname
    required: true
  git_user: 
    description: Your git username
    required: false
    default: github-actions[bot]
  git_email:
    description: Your git email
    required: false
    default: github-actions[bot]@users.noreply.github.com
outputs:
  readme:
    description: The generated readme content
runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v6
      with:
        repository: ssiyad/readme-fetch
        path: readme_fetch
    - name: Cargo run
      run: |
        cd readme_fetch
        cargo run > ../readme.md
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.repository_owner }}
        FETCH_USER: ${{ inputs.user }}
        FETCH_HOST: ${{ inputs.host }}
      shell: bash
    - name: Commit and push Readme
      if: ${{ inputs.dry_run != 'yes' }}
      run: |
        git config --global user.name "${{ inputs.git_user }}"
        git config --global user.email "${{ inputs.git_email }}"
        git add readme.md
        git commit -m "update readme with readme-fetch" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      shell: bash
